---
language: node_js
node_js:
  - "10"

sudo: false
dist: trusty

cache:
  directories:
    - $HOME/.npm

env:
  global:
    - JOBS=1

script:
  - npm run test:unit
  - npm run lint
  - npm run build -- -prod