---
language: node_js
node_js:
  - "10"

sudo: false
dist: trusty

cache:
  directories:
    - $HOME/.npm

env:
  global:
    - JOBS=1

script:
  - npm run test:unit
  - npm run lint
  - npm run build
  - cd dist/
  - git init
  - git add -A
  - git commit -m 'deploy'
  - git push -f git@github.com:shijiezhou1/vuejs-rpc-game.git master:gh-pages