---
language: node_js
node_js:
  - "8"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
  global:
    - JOBS=1

script:
  - npm test:unit
  - npm run lint
  - npm run build -- -prod